### ISSUE TITLE
[BUG] `signal-desktop`'s icon doesn't show in the taskbar

### ISSUE THREAD

**Issue by alfdupont** [nwg-piotr/nwg-panel#140]
**Describe the bug**
Regardless of the chosen icon theme (Adwaita, Beautyline, Papirus), when `signal-desktop` is open, its button in the taskbar is present but has no icon

**To Reproduce**
1. Launch `signal-desktop`
2. See that despite the window being open, the button in the taskbar has no icon on it

**Expected behavior**
As for other applications, I expected to see the icon, since it is present in the relevant `/usr/share/icons` directory

**Screenshots**
![image](https://user-images.githubusercontent.com/93726722/184804754-1d01b486-9f1c-4eda-baad-1d0da8a01522.png)

**Desktop (please complete the following information):**
 - Linux distribution: `Archlinux 5.19.1-arch2-1`
 - Sway version `sway -v`: `sway version 1.7`
 - Panel version `nwg-panel -v`: `nwg-panel version 0.7.4`

**Additional context**

**Comment by nwg-piotr** [comment]
This is actually a bug, not in the panel, but in Signal packaging: ambiguous names. The desktop file should be called `signal.desktop`, not `signal-desktop.desktop`, since the `window_class` value is "Signal".

You may work it around on your side:

1. Copy `/usr/share/applications/signal-desktop.desktop` to `~/.local/share/applications/` and rename it to `signal.desktop`.
2. To avoid duplicate icon in launchers, copy `/usr/share/applications/signal-desktop.desktop` to `~/.local/share/applications/` again, edit the destination file and add `NoDisplay=true` at the bottom.
