### ISSUE TITLE
Issue with brightness percentage scale [BUG]

### ISSUE THREAD

**Issue by Brittle73** [nwg-piotr/nwg-panel#151]
**Describe the bug**
Can't figure out how to show accurate brightnessctl percentage.

**To Reproduce**
It just happens.

**Expected behavior**
Panel should display 0%-100%

**Screenshots**
None yet, can provide later if necessary.

**Desktop (please complete the following information):**
 - Arch
 - Sway version 1.7
 - Panel version 0.7.8
 - Surface Pro 6

**Additional context**
Sorry to create a bug here, let me know if it belongs elsewhere. 

I am unable to get accurate brightness percentage in the panel using brightnessctl. I have the Surface type cover keys working and the brightness reflects accurately everywhere except on this panel. Currently brightnessctl i shows me at 33% (2471, max: 7500), but the panel shows 969%... It does appear to scale, but obviously I would like for it to be 0-100% and define a minimum. The slider inside the panel does change the brightness, but then it just bounces back up to 100% on the slider. Which then shows at the top in the thousands until I use the hardware keys or manually set brightnessctl.

I have tried checking in the config and style sheet, but am apparently missing something. I tried the configuration utility and leaving them blank, selecting brightnessctl and leaving device blank, and entering "brightnessctl," "Intel_Backlight," "intel_backlight," "backlight." Same results across the board. I have toggled in and out of settings in the configuration and set brightnessctl to exponential and back again.

Is there some dumb setting that I missed?

Thanks!

Edit: didn't see much out there on this issue, so I figured documenting it may help others

**Comment by nwg-piotr** [comment]
I always use the `light` package, so I'm not sure if `brightnessctl` still works as expected. Something might have changed over time. I'll check it as soon as I'm back home, with some laptop in range.

**Comment by nwg-piotr** [comment]
Sorry, I can't reproduce the issue on my side. It works well on `brightnessctl` (version 0.5.1), with and without the backlight device specified. Values returned by `brightnessctl -g` should be in range 0 - 255, so *"33% (2471, max: 7500)"* makes no sense.

I suggest (not necessarily in this order):

- check / use the proper backlight device name: `brightnessctl l`. Maybe it's not "intel_backlight"?
- try the `acpi_backlight=vendor` kernel flag;
- try the [light](https://github.com/haikarainen/light) package instead of `brightnessctl`.

**Comment by nwg-piotr** [comment]
Reopen, please, if the fix above doesn't help.
