### ISSUE TITLE
[BUG] After clicking swaync icon on Hyprland, clicking anywhere on the panel brings SwayNC up.

### ISSUE THREAD

**Issue by rb-andrade** [nwg-piotr/nwg-panel#199]
**Describe the bug**
After clicking SwayNC icon with preset-2 clicking anywhere on the bar brings SwayNC up.

**To Reproduce**
1. Click on swaync icon using preset-2 with mouse or touchpad
2. Click on swaync icon again to close it.
3. Clicking on any other icons in the nwg-panel with bring swaync up and not the clicked icon.

**Expected behavior**
Clicking on the other icons should execute the clicked icon command.

**Desktop (please complete the following information):**
 - Tested both on Arch Linux and Alpine Linux
 - Hyprland v0.23.0beta
 - nwg-panel v0.8.2

**Comment by rb-andrade** [comment]
Clicking using the touchscreen works though.

**Comment by nwg-piotr** [comment]
I haven't investigated it yet, but I think it's a swaync property. I'm not saiyng "issue", since it's **Sway** Notification Center. The gtk-layer-shell  lib behaves differently on Hyprland. E.g. nwg-panel HyprlandTaskbar module must not be placed neither on `bottom` nor `background` layer, or the right-click menu lands below windows. If you set a panel layer like this, and add HyprlandTaskbar to it, I [silently change](https://github.com/nwg-piotr/nwg-panel/blob/78c51ce6a5336301e351230de210f55479cafa77/nwg_panel/main.py#L297) the layer to `top`.

I'll dig a bit more into it soon. Maybe it could be workaround-ed with some config option? If not, we'll have to ask Eric for help.

**Comment by nwg-piotr** [comment]
After some testing: the bug, whatever it is, may lay on my side. I tried to display the swaync icon as a button, and it behaved well. Interesting...
