### ISSUE TITLE
[Feature request] Display only workspaces bound to output

### ISSUE THREAD

**Issue by radrow** [nwg-piotr/nwg-panel#231]
**Is your feature request related to a problem? Please describe.**
My problem is that I am using n monitors and n^2 workspaces. It happens very often that I lose a workspace not knowing on which screen it was. While searching for it I have to switch through O(all) workspaces, during what I change active workspaces on my other screens. When I finally find it, I have to bring back the workspaces I had on previous screens, which loops the whole procedure as I rarely remember which ones those were.

**Describe the solution you'd like**
I would like to be able to display on each nwg-panel of every monitor only those workspaces that are bound to it. So if workspaces 1,2,3 are on monitor X and 4,5 are on Y, the setup would look like 

```
monitor X:
  swg-panel:
    workspaces:
    - 1
    - 2
    - 3
monitor Y:
  swg-panel:
    workspaces:
    - 4
    - 5 
```

If it makes sense. Of course, this should be a switched behaviour.

**Describe alternatives you've considered**
Sticky notes to put on my monitors so I remember what is where

**Additional context**
null

**Comment by nwg-piotr** [comment]
I'll check what I can do.

**Comment by nwg-piotr** [comment]
The problem is, that a workspace, even if bound to an monitor, does not exist in the `hyprctl workspaces` output if empty. So, you'd only see non-empty workspace numbers in each module, having this option turned on. Currently, I'm working on 3 outputs with just one non-empty workspace on each, and I only see one WS number in each workspaces module. Dunno if it makes sense.
