### ISSUE TITLE
switch between players

### ISSUE THREAD

**Issue by Visual-Dawg** [nwg-piotr/nwg-panel#303]
I want to switch the active player on the bar as Chromium always takes precedence over my music player.
The command `playerctld shift` does that. 
Now I need a way to run the command when interacting with the widget. 
On scroll or on right-click seems like a good way for that. 

As from here:  https://github.com/nwg-piotr/nwg-panel/issues/172#issuecomment-1377456209_

**Comment by nwg-piotr** [comment]
It's not that simple, as what the module displays is always player #0. We will need more changes in the code.

**Comment by nwg-piotr** [comment]
OK, we do not need playerctld. We only need to watch all players, instead of player #0, and switch between them. It seems to work perfectly well on my side.

I added a label `player number`/`number or players` that appears when have more than one player. It should do the job.

![obraz](https://github.com/nwg-piotr/nwg-panel/assets/20579136/e3fd4a50-66e6-4841-9e42-dac7378bada3)
