### ISSUE TITLE
[Hyprland Workspaces] All outputs toggle

### ISSUE THREAD

**Issue by IceDBorn** [nwg-piotr/nwg-panel#349]
I want the hyprland workspaces module to show workspaces only available on the current monitor. The hyprland taskbar module has this functionality, under a toggle called "All Outputs".

**Comment by nwg-piotr** [comment]
If a workspace is empty and not shown at the moment, it does not exist in Hyprland, event if its ID or name is associated to an output in your config file.

![obraz](https://github.com/user-attachments/assets/ab138f58-88a4-4910-a69e-06571bc6ee24)

The module does not parse your config file, is Hyprland's job. If I told the module to only show existing workspaces on each monitor, in the picture above you'd only see one number: 4 - even if 5 and 6 are configured to show up on this output. Because 5 and 6 are empty, and `hyprctl workspaces` won't list them. That's why we have no "All outputs" switch for this module.

**Comment by IceDBorn** [comment]
I did not ask for this. For example, I have 2 monitors. Let's say the first workspace for each monitor is currently active with windows. The workspaces modules will print both workspace 1 of monitor 1 and workspace 1 of monitor 2. What I would like is to only see the active workspaces of the panel's monitor. Whereas now, the panel shows `ALL` active workspaces, regardless the monitor.

**Comment by nwg-piotr** [comment]
In this case you'll only see 1 WS number on the monitor. This makes little sense to me.
