### ISSUE TITLE
Multilanguage support

### ISSUE THREAD

**Issue by brainrom** [nwg-piotr/nwg-panel#4]
Exit menu can be translated in config file, but not "To workspace...", "Kill", etc. and have a language mess in system is not cool. So, minimal multilanguage will be very nice. I can add a translation engine and Russian translation by myself and then PR into master.

**Comment by nwg-piotr** [comment]
This must wait. Having finished the config GUI (current progress: 30%), I'm going to check if coding the panel itself in Go brings some significant performance improvement. I'm not going to maintain versions in two languages in the future, so new features should be added in the finally chosen  lang - python or golang.

**Comment by brainrom** [comment]
IMHO, panel should stay on Python. This brings much more flexibility (like Qtile) with insufficient performance drawbacks. Even on my Intel Celeron tablet, nwg-panel works a lot faster than C++ written waybar.

**Comment by nwg-piotr** [comment]
Well, python goes better with GTK due to the object-oriented approach. Also the code would be easier to maintain, and more likely to gain contributors. Some time ago I coded the same GTK-based stuff in python, and then again in Go, and the Go code is twice as long. But it works almost 2 times faster. There are pros and cons...
