### ISSUE TITLE
Curstom workspace style in swaytaskbar

### ISSUE THREAD

**Issue by tmarti2** [nwg-piotr/nwg-panel#42]
Hi,
I'm trying to configure my bar so it looks like my waybar, but I'm having some trouble figuring out how to do it.
![image](https://user-images.githubusercontent.com/32908972/112314917-dc668500-8ca9-11eb-8cdf-9571f3abc005.png)

the top one is made with your application, and the other one with waybar.
In waybar I have :
Workspaces (focused workspace in blue) - Focused window's title
and with yours :
Workspace 1 - all windows' titles - Workspace 2
At the moment I don't really care about margins etc, I'm juste trying to get everything else to work.
So is it possible, via the css file, to do something like this ?
I tried few things but nothing worked so far.
Thanks

**Comment by nwg-piotr** [comment]
There's no module to show just the focused window title. It would be easy to develop, but a bit useless, as we have the SwayTaskbar module. You can configure what to show in it: 

- windows from all outputs / from current output
- from all workspaces / from active workspace

If it comes to the SwayWorkspaces module: it displays just static buttons, since I saw no actual need to have such a module at all. :) Now I changed my mind: it may be useful when you don't use the taskbar module. I'll add some pointer to indicate which workspace we're currently on soon, as I need it to get comfortable with the sway dock I'm currently working on.

**Comment by tmarti2** [comment]
Ok thanks, I'll leave it like this for now.

**Comment by nwg-piotr** [comment]
Hope you'll like it (top left corner). By the way it goes well with the dock.

![2021-03-25-015525_screenshot.png](https://scrot.cloud/images/2021/03/25/2021-03-25-015525_screenshot.png)

**Comment by nwg-piotr** [comment]
Seems to work well. Merged into master, but a release must wait till I wake up. It's 5:30 am. :)

**Comment by nwg-piotr** [comment]
Sorry for the delay: when running from PyCharm, it happened to die silently several times, with no obvious reason. It needs some more testing.

**Comment by tmarti2** [comment]
Np 👌
